github:
  features:
    # Enable issue management
    issues: true
    # Enable wiki
    wiki: true

  protected_branches:
notifications:
  commits:      commits@rocketmq.apache.org
  issues:       commits@rocketmq.apache.org
  pullrequests: commits@rocketmq.apache.org
  jobs:         commits@rocketmq.apache.org
  discussions:  dev@rocketmq.apache.org
